ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS end_date DATETIME NULL,
    ADD COLUMN IF NOT EXISTS end_time VARCHAR(10) NULL,
    ADD COLUMN IF NOT EXISTS activity_type VARCHAR(50) NOT NULL DEFAULT 'generic',
    ADD COLUMN IF NOT EXISTS priority VARCHAR(50) NOT NULL DEFAULT 'normal',
    ADD COLUMN IF NOT EXISTS location VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS reminder_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS outcome VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS internal_notes TEXT NULL,
    ADD COLUMN IF NOT EXISTS all_day BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE tasks
SET activity_type = 'generic'
WHERE activity_type IS NULL OR activity_type = '';

UPDATE tasks
SET priority = 'normal'
WHERE priority IS NULL OR priority = '';
